IF OBJECT_ID('dbo.A1_torques', 'U') IS NOT NULL
 DROP TABLE dbo.A1_torques;
GO
-- Create the table in the specified schema
CREATE TABLE dbo.A1_torques
(
 Id int IDENTITY(1,1) PRIMARY KEY, -- primary key column
 CLM nvarchar(255) NULL,
 PN nvarchar(255) NULL,
 PP_Cover_P_1 float NULL,
 PP_Cover_P_2 float NULL,
 PP_Cover_N_1 float NULL,
 PP_Cover_N_2 float NULL,
 PP_Module_1_P float NULL,
 PP_Module_1_N float NULL,
 Power_Plate_1 float NULL,
 Power_Plate_2 float NULL,
 Power_Plate_3 float NULL,
 Power_Plate_4 float NULL,
 Power_Plate_5 float NULL,
 Power_Plate_6 float NULL,
 Power_Plate_7 float NULL,
 Module_P_1 float NULL,
 Module_N_1 float NULL,
 Module_SN nvarchar(255) NULL,
 Cell_1_N float NULL,
 Cell_1_P float NULL,
 Cell_2_N float NULL,
 Cell_2_P float NULL,
 Cell_3_N float NULL,
 Cell_3_P float NULL,
 Cell_4_N float NULL,
 Cell_4_P float NULL,
 Cell_5_N float NULL,
 Cell_5_P float NULL,
 Cell_6_N float NULL,
 Cell_6_P float NULL,
 Cell_7_N float NULL,
 Cell_7_P float NULL,
 Cell_8_N float NULL,
 Cell_8_P float NULL,
 Cell_9_N float NULL,
 Cell_9_P float NULL,
 Cell_10_N float NULL,
 Cell_10_P float NULL,
 Cell_11_N float NULL,
 Cell_11_P float NULL,
 Cell_12_N float NULL,
 Cell_12_P float NULL,
 Cell_13_N float NULL,
 Cell_13_P float NULL,
 Cell_14_N float NULL,
 Cell_14_P float NULL,
 Cell_1_Voltage float NULL,
 Cell_2_Voltage float NULL,
 Cell_3_Voltage float NULL,
 Cell_4_Voltage float NULL,
 Cell_5_Voltage float NULL,
 Cell_6_Voltage float NULL,
 Cell_7_Voltage float NULL,
 Cell_8_Voltage float NULL,
 Cell_9_Voltage float NULL,
 Cell_10_Voltage float NULL,
 Cell_11_Voltage float NULL,
 Cell_12_Voltage float NULL,
 Cell_13_Voltage float NULL,
 Cell_14_Voltage float NULL,
 Total_Voltage float NULL,
 Information TEXT NULL,
 RepairComponents TEXT NULL
);
GO