IF OBJECT_ID('dbo.A1_torques', 'U') IS NOT NULL
 DROP TABLE dbo.A1_torques;
GO
-- Create the table in the specified schema
CREATE TABLE [dbo].[A1_torques] (
    [Id]               INT            IDENTITY (1, 1) NOT NULL,
    [CLM]              NVARCHAR (255) NULL,
    [PN]               NVARCHAR (255) NULL,
    [PP_Cover_P_1]     FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_PP_Cover_P_1] DEFAULT ((-1)) NULL,
    [PP_Cover_P_2]     FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_PP_Cover_P_2] DEFAULT ((-1)) NULL,
    [PP_Cover_N_1]     FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_PP_Cover_N_1] DEFAULT ((-1)) NULL,
    [PP_Cover_N_2]     FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_PP_Cover_N_2] DEFAULT ((-1)) NULL,
    [PP_Module_1_P]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_PP_Module_1_P] DEFAULT ((-1)) NULL,
    [PP_Module_1_N]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_PP_Module_1_N] DEFAULT ((-1)) NULL,
    [Power_Plate_1]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Power_Plate_1] DEFAULT ((-1)) NULL,
    [Power_Plate_2]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Power_Plate_2] DEFAULT ((-1)) NULL,
    [Power_Plate_3]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Power_Plate_3] DEFAULT ((-1)) NULL,
    [Power_Plate_4]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Power_Plate_4] DEFAULT ((-1)) NULL,
    [Power_Plate_5]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Power_Plate_5] DEFAULT ((-1)) NULL,
    [Power_Plate_6]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Power_Plate_6] DEFAULT ((-1)) NULL,
    [Power_Plate_7]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Power_Plate_7] DEFAULT ((-1)) NULL,
    [Module_P_1]       FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Module_P_1] DEFAULT ((-1)) NULL,
    [Module_N_1]       FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Module_N_1] DEFAULT ((-1)) NULL,
    [Module_SN]        NVARCHAR (255) NULL,
    [Cell_1_N]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_1_N] DEFAULT ((-1)) NULL,
    [Cell_1_P]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_1_P] DEFAULT ((-1)) NULL,
    [Cell_2_N]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_2_N] DEFAULT ((-1)) NULL,
    [Cell_2_P]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_2_P] DEFAULT ((-1)) NULL,
    [Cell_3_N]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_3_N] DEFAULT ((-1)) NULL,
    [Cell_3_P]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_3_P] DEFAULT ((-1)) NULL,
    [Cell_4_N]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_4_N] DEFAULT ((-1)) NULL,
    [Cell_4_P]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_4_P] DEFAULT ((-1)) NULL,
    [Cell_5_N]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_5_N] DEFAULT ((-1)) NULL,
    [Cell_5_P]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_5_P] DEFAULT ((-1)) NULL,
    [Cell_6_N]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_6_N] DEFAULT ((-1)) NULL,
    [Cell_6_P]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_6_P] DEFAULT ((-1)) NULL,
    [Cell_7_N]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_7_N] DEFAULT ((-1)) NULL,
    [Cell_7_P]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_7_P] DEFAULT ((-1)) NULL,
    [Cell_8_N]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_8_N] DEFAULT ((-1)) NULL,
    [Cell_8_P]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_8_P] DEFAULT ((-1)) NULL,
    [Cell_9_N]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_9_N] DEFAULT ((-1)) NULL,
    [Cell_9_P]         FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_9_P] DEFAULT ((-1)) NULL,
    [Cell_10_N]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_10_N] DEFAULT ((-1)) NULL,
    [Cell_10_P]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_10_P] DEFAULT ((-1)) NULL,
    [Cell_11_N]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_11_N] DEFAULT ((-1)) NULL,
    [Cell_11_P]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_11_P] DEFAULT ((-1)) NULL,
    [Cell_12_N]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_12_N] DEFAULT ((-1)) NULL,
    [Cell_12_P]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_12_P] DEFAULT ((-1)) NULL,
    [Cell_13_N]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_13_N] DEFAULT ((-1)) NULL,
    [Cell_13_P]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_13_P] DEFAULT ((-1)) NULL,
    [Cell_14_N]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_14_N] DEFAULT ((-1)) NULL,
    [Cell_14_P]        FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_14_P] DEFAULT ((-1)) NULL,
    [Cell_1_Voltage]   FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_1_Voltage] DEFAULT ((-1)) NULL,
    [Cell_2_Voltage]   FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_2_Voltage] DEFAULT ((-1)) NULL,
    [Cell_3_Voltage]   FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_3_Voltage] DEFAULT ((-1)) NULL,
    [Cell_4_Voltage]   FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_4_Voltage] DEFAULT ((-1)) NULL,
    [Cell_5_Voltage]   FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_5_Voltage] DEFAULT ((-1)) NULL,
    [Cell_6_Voltage]   FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_6_Voltage] DEFAULT ((-1)) NULL,
    [Cell_7_Voltage]   FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_7_Voltage] DEFAULT ((-1)) NULL,
    [Cell_8_Voltage]   FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_8_Voltage] DEFAULT ((-1)) NULL,
    [Cell_9_Voltage]   FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_9_Voltage] DEFAULT ((-1)) NULL,
    [Cell_10_Voltage]  FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_10_Voltage] DEFAULT ((-1)) NULL,
    [Cell_11_Voltage]  FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_11_Voltage] DEFAULT ((-1)) NULL,
    [Cell_12_Voltage]  FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_12_Voltage] DEFAULT ((-1)) NULL,
    [Cell_13_Voltage]  FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_13_Voltage] DEFAULT ((-1)) NULL,
    [Cell_14_Voltage]  FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Cell_14_Voltage] DEFAULT ((-1)) NULL,
    [Total_Voltage]    FLOAT (53)     CONSTRAINT [DEFAULT_A1_torques_Total_Voltage] DEFAULT ((-1)) NULL,
    [Information]      TEXT           NULL,
    [RepairComponents] TEXT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO