IF OBJECT_ID('dbo.A2_torques', 'U') IS NOT NULL
 DROP TABLE dbo.A2_torques;
GO
-- Create the table in the specified schema
CREATE TABLE [dbo].[A2_torques] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [CLM]               NVARCHAR (255) NULL,
    [PN]                NVARCHAR (255) NULL,
    [PP_Cover_P_1]      FLOAT (53)     NULL,
    [PP_Cover_P_2]      FLOAT (53)     NULL,
    [PP_Cover_N_1]      FLOAT (53)     NULL,
    [PP_Cover_N_2]      FLOAT (53)     NULL,
    [PP_Module_1_P]     FLOAT (53)     NULL,
    [PP_Module_1_N]     FLOAT (53)     NULL,
    [PP_Module_2_P]     FLOAT (53)     NULL,
    [PP_Module_2_N]     FLOAT (53)     NULL,
    [Power_Plate_1]     FLOAT (53)     NULL,
    [Power_Plate_2]     FLOAT (53)     NULL,
    [Power_Plate_3]     FLOAT (53)     NULL,
    [Power_Plate_4]     FLOAT (53)     NULL,
    [Power_Plate_5]     FLOAT (53)     NULL,
    [Power_Plate_6]     FLOAT (53)     NULL,
    [Power_Plate_7]     FLOAT (53)     NULL,
    [Module_P_1]        FLOAT (53)     NULL,
    [Module_P_2]        FLOAT (53)     NULL,
    [Module_N_1]        FLOAT (53)     NULL,
    [Module_N_2]        FLOAT (53)     NULL,
    [Module_A_SN]       NVARCHAR (255) NULL,
    [A_Cell_1_N]        FLOAT (53)     NULL,
    [A_Cell_1_P]        FLOAT (53)     NULL,
    [A_Cell_2_N]        FLOAT (53)     NULL,
    [A_Cell_2_P]        FLOAT (53)     NULL,
    [A_Cell_3_N]        FLOAT (53)     NULL,
    [A_Cell_3_P]        FLOAT (53)     NULL,
    [A_Cell_4_N]        FLOAT (53)     NULL,
    [A_Cell_4_P]        FLOAT (53)     NULL,
    [A_Cell_5_N]        FLOAT (53)     NULL,
    [A_Cell_5_P]        FLOAT (53)     NULL,
    [A_Cell_6_N]        FLOAT (53)     NULL,
    [A_Cell_6_P]        FLOAT (53)     NULL,
    [A_Cell_7_N]        FLOAT (53)     NULL,
    [A_Cell_7_P]        FLOAT (53)     NULL,
    [A_Cell_8_N]        FLOAT (53)     NULL,
    [A_Cell_8_P]        FLOAT (53)     NULL,
    [A_Cell_9_N]        FLOAT (53)     NULL,
    [A_Cell_9_P]        FLOAT (53)     NULL,
    [A_Cell_10_N]       FLOAT (53)     NULL,
    [A_Cell_10_P]       FLOAT (53)     NULL,
    [A_Cell_11_N]       FLOAT (53)     NULL,
    [A_Cell_11_P]       FLOAT (53)     NULL,
    [A_Cell_12_N]       FLOAT (53)     NULL,
    [A_Cell_12_P]       FLOAT (53)     NULL,
    [A_Cell_13_N]       FLOAT (53)     NULL,
    [A_Cell_13_P]       FLOAT (53)     NULL,
    [A_Cell_14_N]       FLOAT (53)     NULL,
    [A_Cell_14_P]       FLOAT (53)     NULL,
    [A_Cell_1_Voltage]  FLOAT (53)     NULL,
    [A_Cell_2_Voltage]  FLOAT (53)     NULL,
    [A_Cell_3_Voltage]  FLOAT (53)     NULL,
    [A_Cell_4_Voltage]  FLOAT (53)     NULL,
    [A_Cell_5_Voltage]  FLOAT (53)     NULL,
    [A_Cell_6_Voltage]  FLOAT (53)     NULL,
    [A_Cell_7_Voltage]  FLOAT (53)     NULL,
    [A_Cell_8_Voltage]  FLOAT (53)     NULL,
    [A_Cell_9_Voltage]  FLOAT (53)     NULL,
    [A_Cell_10_Voltage] FLOAT (53)     NULL,
    [A_Cell_11_Voltage] FLOAT (53)     NULL,
    [A_Cell_12_Voltage] FLOAT (53)     NULL,
    [A_Cell_13_Voltage] FLOAT (53)     NULL,
    [A_Cell_14_Voltage] FLOAT (53)     NULL,
    [A_Total_Voltage]   FLOAT (53)     NULL,
    [A_Information]     TEXT           NULL,
    [Module_B_SN]       NVARCHAR (255) NULL,
    [B_Cell_1_N]        FLOAT (53)     NULL,
    [B_Cell_1_P]        FLOAT (53)     NULL,
    [B_Cell_2_N]        FLOAT (53)     NULL,
    [B_Cell_2_P]        FLOAT (53)     NULL,
    [B_Cell_3_N]        FLOAT (53)     NULL,
    [B_Cell_3_P]        FLOAT (53)     NULL,
    [B_Cell_4_N]        FLOAT (53)     NULL,
    [B_Cell_4_P]        FLOAT (53)     NULL,
    [B_Cell_5_N]        FLOAT (53)     NULL,
    [B_Cell_5_P]        FLOAT (53)     NULL,
    [B_Cell_6_N]        FLOAT (53)     NULL,
    [B_Cell_6_P]        FLOAT (53)     NULL,
    [B_Cell_7_N]        FLOAT (53)     NULL,
    [B_Cell_7_P]        FLOAT (53)     NULL,
    [B_Cell_8_N]        FLOAT (53)     NULL,
    [B_Cell_8_P]        FLOAT (53)     NULL,
    [B_Cell_9_N]        FLOAT (53)     NULL,
    [B_Cell_9_P]        FLOAT (53)     NULL,
    [B_Cell_10_N]       FLOAT (53)     NULL,
    [B_Cell_10_P]       FLOAT (53)     NULL,
    [B_Cell_11_N]       FLOAT (53)     NULL,
    [B_Cell_11_P]       FLOAT (53)     NULL,
    [B_Cell_12_N]       FLOAT (53)     NULL,
    [B_Cell_12_P]       FLOAT (53)     NULL,
    [B_Cell_13_N]       FLOAT (53)     NULL,
    [B_Cell_13_P]       FLOAT (53)     NULL,
    [B_Cell_14_N]       FLOAT (53)     NULL,
    [B_Cell_14_P]       FLOAT (53)     NULL,
    [B_Cell_1_Voltage]  FLOAT (53)     NULL,
    [B_Cell_2_Voltage]  FLOAT (53)     NULL,
    [B_Cell_3_Voltage]  FLOAT (53)     NULL,
    [B_Cell_4_Voltage]  FLOAT (53)     NULL,
    [B_Cell_5_Voltage]  FLOAT (53)     NULL,
    [B_Cell_6_Voltage]  FLOAT (53)     NULL,
    [B_Cell_7_Voltage]  FLOAT (53)     NULL,
    [B_Cell_8_Voltage]  FLOAT (53)     NULL,
    [B_Cell_9_Voltage]  FLOAT (53)     NULL,
    [B_Cell_10_Voltage] FLOAT (53)     NULL,
    [B_Cell_11_Voltage] FLOAT (53)     NULL,
    [B_Cell_12_Voltage] FLOAT (53)     NULL,
    [B_Cell_13_Voltage] FLOAT (53)     NULL,
    [B_Cell_14_Voltage] FLOAT (53)     NULL,
    [B_Total_Voltage]   FLOAT (53)     NULL,
    [B_Information]     TEXT           NULL,
    [RepairComponents]  TEXT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO