IF OBJECT_ID('dbo.DataAnalysis_BB', 'U') IS NOT NULL
 DROP TABLE dbo.DataAnalysis_BB;
GO
-- Create the table in the specified schema
CREATE TABLE dbo.DataAnalysis_BB
(
 Id int IDENTITY(1,1) PRIMARY KEY, -- primary key column
 CLM nvarchar(255) NULL,
 Battery nvarchar(255) NULL,
 BMS nvarchar(255) NULL,
 Visual_State nvarchar(10) NULL,
 Visual_State_Note TEXT NULL,
 PrtScn nvarchar(10) NULL,
 BrandID nvarchar(255) NULL,
 ModuleVoltage_State nvarchar(10) NULL,
 ModuleVoltage float NULL,
 Funct_BMS_State nvarchar(10) NULL,
 Funct_BMS TEXT NULL,
 WinDiag_State nvarchar(10) NULL,
 WinDiag TEXT NULL,
 ActualCurr_State nvarchar(10) NULL,
 ActualCurr TEXT NULL,
 Presence_State nvarchar(10) NULL,
 Presence_State12 nvarchar(10) NULL,
 Presence_State24 nvarchar(10) NULL,
 Presence TEXT NULL,
 SMU_State nvarchar(10) NULL,
 SMU_Val float NULL,
 SMU TEXT NULL,
 Current_Const_State nvarchar(10) NULL,
 Current_Const_IG nvarchar(50) NULL,
 Current_Const_IO nvarchar(50) NULL,
 CAN_Speed_State nvarchar(10) NULL,
 CAN_Speed_Val nvarchar(50) NULL,
 CAN_Speed_Kbps nvarchar(50) NULL,
 CRC_of_SW_State nvarchar(10) NULL,
 CRC_of_SW TEXT NULL,
 BB_State nvarchar(10) NULL,
 BB TEXT NULL,
 Saft_Fault_Code_1 int NULL, Kion_Fault_Code_1 int NULL, Kion_DTC_1 int NULL,
 Saft_Fault_Code_2 int NULL, Kion_Fault_Code_2 int NULL, Kion_DTC_2 int NULL,
 Saft_Fault_Code_3 int NULL, Kion_Fault_Code_3 int NULL, Kion_DTC_3 int NULL,
 Saft_Fault_Code_4 int NULL, Kion_Fault_Code_4 int NULL, Kion_DTC_4 int NULL,
 Saft_Fault_Code_5 int NULL, Kion_Fault_Code_5 int NULL, Kion_DTC_5 int NULL,
 Saft_Fault_Code_6 int NULL, Kion_Fault_Code_6 int NULL, Kion_DTC_6 int NULL,
 Saft_Fault_Code_7 int NULL, Kion_Fault_Code_7 int NULL, Kion_DTC_7 int NULL,
 Saft_Fault_Code_8 int NULL, Kion_Fault_Code_8 int NULL, Kion_DTC_8 int NULL,
 Saft_Fault_Code_9 int NULL, Kion_Fault_Code_9 int NULL, Kion_DTC_9 int NULL,
 Saft_Fault_Code_10 int NULL, Kion_Fault_Code_10 int NULL, Kion_DTC_10 int NULL,
 Saft_Fault_Code_11 int NULL, Kion_Fault_Code_11 int NULL, Kion_DTC_11 int NULL,
 Saft_Fault_Code_12 int NULL, Kion_Fault_Code_12 int NULL, Kion_DTC_12 int NULL,
 Charging_State nvarchar(10) NULL,
 Charging TEXT NULL,
 Discharging_State nvarchar(10) NULL,
 Discharging TEXT NULL,
 RTC_State nvarchar(10) NULL,
 RTC TEXT NULL,
 BMS_Tested_State nvarchar(10) NULL,
 BMS_Tested TEXT NULL,
 Replacement_State nvarchar(10) NULL,
 Replacement TEXT NULL,
 CriticalFault_State nvarchar(10) NULL,
 CriticalFault TEXT NULL,
 CBIT_State nvarchar(10) NULL,
 CBIT TEXT NULL,
 Capacity_State nvarchar(10) NULL,
 Capacity TEXT NULL,
 Contiunity_State nvarchar(10) NULL,
 Contiunity TEXT NULL,
 Function_State nvarchar(10) NULL,
 Function_Text TEXT NULL,
 Status_State nvarchar(10) NULL,
 Status TEXT NULL,
 Warranty_State nvarchar(10) NULL,
 Warranty TEXT NULL,
 Production_Date nvarchar(50) NULL,
 Now_Date nvarchar(50) NULL
);
GO