IF OBJECT_ID('dbo.DataAnalysis_BB', 'U') IS NOT NULL
 DROP TABLE dbo.DataAnalysis_BB;
GO
-- Create the table in the specified schema
CREATE TABLE [dbo].[DataAnalysis_BB] (
    [Id]                  INT            IDENTITY (1, 1) NOT NULL,
    [CLM]                 NVARCHAR (255) NULL,
    [Battery]             NVARCHAR (255) NULL,
    [BMS]                 NVARCHAR (255) NULL,
    [Visual_State]        NVARCHAR (10)  NULL,
    [Visual_State_Note]   TEXT           NULL,
    [PrtScn]              NVARCHAR (10)  NULL,
    [BrandID]             NVARCHAR (255) NULL,
    [ModuleVoltage_State] NVARCHAR (10)  NULL,
    [ModuleVoltage]       FLOAT (53)     NULL,
    [Funct_BMS_State]     NVARCHAR (10)  NULL,
    [Funct_BMS]           TEXT           NULL,
    [WinDiag_State]       NVARCHAR (10)  NULL,
    [WinDiag]             TEXT           NULL,
    [ActualCurr_State]    NVARCHAR (10)  NULL,
    [ActualCurr]          TEXT           NULL,
    [Presence_State]      NVARCHAR (10)  NULL,
    [Presence_State12]    NVARCHAR (10)  NULL,
    [Presence_State24]    NVARCHAR (10)  NULL,
    [Presence]            TEXT           NULL,
    [SMU_State]           NVARCHAR (10)  NULL,
    [SMU_Val]             FLOAT (53)     NULL,
    [SMU]                 TEXT           NULL,
    [Current_Const_State] NVARCHAR (10)  NULL,
    [Current_Const_IG]    NVARCHAR (50)  NULL,
    [Current_Const_IO]    NVARCHAR (50)  NULL,
    [CAN_Speed_State]     NVARCHAR (10)  NULL,
    [CAN_Speed_Val]       NVARCHAR (50)  NULL,
    [CAN_Speed_Kbps]      NVARCHAR (50)  NULL,
    [CRC_of_SW_State]     NVARCHAR (10)  NULL,
    [CRC_of_SW]           TEXT           NULL,
    [BB_State]            NVARCHAR (10)  NULL,
    [BB]                  TEXT           NULL,
    [Saft_Fault_Code_1]   INT            NULL,
    [Kion_Fault_Code_1]   INT            NULL,
    [Kion_DTC_1]          INT            NULL,
    [Saft_Fault_Code_2]   INT            NULL,
    [Kion_Fault_Code_2]   INT            NULL,
    [Kion_DTC_2]          INT            NULL,
    [Saft_Fault_Code_3]   INT            NULL,
    [Kion_Fault_Code_3]   INT            NULL,
    [Kion_DTC_3]          INT            NULL,
    [Saft_Fault_Code_4]   INT            NULL,
    [Kion_Fault_Code_4]   INT            NULL,
    [Kion_DTC_4]          INT            NULL,
    [Saft_Fault_Code_5]   INT            NULL,
    [Kion_Fault_Code_5]   INT            NULL,
    [Kion_DTC_5]          INT            NULL,
    [Saft_Fault_Code_6]   INT            NULL,
    [Kion_Fault_Code_6]   INT            NULL,
    [Kion_DTC_6]          INT            NULL,
    [Saft_Fault_Code_7]   INT            NULL,
    [Kion_Fault_Code_7]   INT            NULL,
    [Kion_DTC_7]          INT            NULL,
    [Saft_Fault_Code_8]   INT            NULL,
    [Kion_Fault_Code_8]   INT            NULL,
    [Kion_DTC_8]          INT            NULL,
    [Saft_Fault_Code_9]   INT            NULL,
    [Kion_Fault_Code_9]   INT            NULL,
    [Kion_DTC_9]          INT            NULL,
    [Saft_Fault_Code_10]  INT            NULL,
    [Kion_Fault_Code_10]  INT            NULL,
    [Kion_DTC_10]         INT            NULL,
    [Saft_Fault_Code_11]  INT            NULL,
    [Kion_Fault_Code_11]  INT            NULL,
    [Kion_DTC_11]         INT            NULL,
    [Saft_Fault_Code_12]  INT            NULL,
    [Kion_Fault_Code_12]  INT            NULL,
    [Kion_DTC_12]         INT            NULL,
    [Charging_State]      NVARCHAR (10)  NULL,
    [Charging]            TEXT           NULL,
    [Discharging_State]   NVARCHAR (10)  NULL,
    [Discharging]         TEXT           NULL,
    [RTC_State]           NVARCHAR (10)  NULL,
    [RTC]                 TEXT           NULL,
    [BMS_Tested_State]    NVARCHAR (10)  NULL,
    [BMS_Tested]          TEXT           NULL,
    [Replacement_State]   NVARCHAR (10)  NULL,
    [Replacement]         TEXT           NULL,
    [CriticalFault_State] NVARCHAR (10)  NULL,
    [CriticalFault]       TEXT           NULL,
    [CBIT_State]          NVARCHAR (10)  NULL,
    [CBIT]                TEXT           NULL,
    [Capacity_State]      NVARCHAR (10)  NULL,
    [Capacity]            TEXT           NULL,
    [Contiunity_State]    NVARCHAR (10)  NULL,
    [Contiunity]          TEXT           NULL,
    [Function_State]      NVARCHAR (10)  NULL,
    [Function_Text]       TEXT           NULL,
    [Status_State]        NVARCHAR (10)  NULL,
    [Status]              TEXT           NULL,
    [Warranty_State]      NVARCHAR (10)  NULL,
    [Warranty]            TEXT           NULL,
    [Production_Date]     NVARCHAR (50)  NULL,
    [Now_Date]            NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO